### ISSUE TITLE
Followed the instructions, it doesn't appear, nothing in logs

### ISSUE THREAD

**Issue by n8vision** [madmicio/Apple-Tv-Card#5]
I followed the (somewhat unclear) instructions and nothing appears in my lovelace dashboard. 

eg this it not clear:

Add a reference `` from (https://github.com/madmicio/Apple-Tv-Card) into your custom components directory. ` inside your resources config:

but I took it to mean click on the 'Add resource' button inside your dashboard setup and add the path in there.

**Comment by thomasdupkavich94** [comment]
Same here did u ever figure it out?

**Comment by n8vision** [comment]
nope! btw for the record I love open source and love the author made this available, but its best to ensure clear documentation and working code to avoid wasting peoples time, ideally :)

**Comment by Freudie** [comment]
I don't know if this is an issue for you, but I managed to get it to work.. I struggled with the same issues .
So first, you need to make sure you are in advanced mode. To do this, you go to your account (click on your profile picture) and look for Advanced. Make sure it's turned on.

When you've added this project to HACS, reboot, then go to Settings --> Dashboards.
In the top right, you can now add resources. Click on the three dots: 
![image](https://github.com/madmicio/Apple-Tv-Card/assets/51196012/5a03f07b-5aed-4a3b-9d2d-1a8cb04e86b7)
Click on it, then you can click on Add resource:
![image](https://github.com/madmicio/Apple-Tv-Card/assets/51196012/73f18763-2665-4869-84fe-0d41e7745925)
These URLs are from the Readme of this project so keep those. Make sure you add the CSS one as well (it's also in the Readme).
I rebooted HA after this step.

So now you can create your dashboard. What you do now is go to Settings --> Dashboards and create a new dashboard. Create one from scratch, create your dashboard with the name and icon you want, then save it:
![image](https://github.com/madmicio/Apple-Tv-Card/assets/51196012/339d79c1-76e2-4975-9e83-11fe7b9f0b77)

Then open it, and you can now create your dashboard. You can copy from the view from the readme: [](https://github.com/madmicio/Apple-Tv-Card?tab=readme-ov-file#lovelace-config-custom-view).
Make sure you change the entity and remote to your own entities.

I have also added the full screen mode and kiosk stuff, so make sure you add that as well. You should now have a working dashboard. 

One remark, the URLs of the images are wrong in the example. It should be like this (for youtube):
/local/community/Apple-Tv-Card/logo/YouTube.png
So make sure the path is correct.

This is mine (I have created a logo for f1tv and HBO max):
```
type: custom:apple-tv-card
entity: media_player.woonkamer
remote: remote.woonkamer
sources:
  - image: /local/community/Apple-Tv-Card/logo/YouTube.png
    source_name: YouTube
  - source_name: Disney+
  - source_name: Netflix
  - source_name: Prime Video
  - image: /local/community/Apple-Tv-Card/logo/f1tv_logo_transparent.png
    source_name: F1 TV
  - image: /local/community/Apple-Tv-Card/logo/HBO-Max-Logo_trans.png
    source_name: HBO Max
full_screen: false
kiosk_mode:
  hide_sidebar: true
  hide_header: true
views:
  - title: Apple tv
    background: >-
      linear-gradient(155deg, rgba(60,66,80,1) 0%, rgba(23,26,37,1) 42%,
      rgba(21,25,35,1) 100%)
    type: custom:apple-tv-card
    entity: media_player.woonkamer
    remote: remote.woonkamer
```
